name: Twitter to Telegram Bot

on:
  workflow_dispatch:
 

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Twitter Telegram bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python twitter_bot.py

      - name: Save latest tweet ID
        run: |
          if [ -f last_tweet_id.txt ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add last_tweet_id.txt
            git diff --cached --quiet || git commit -m "Update last tweet ID"
            git push
          fi
